// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-KxVekNTrEzxLAwiRSq1WVEC7oi2VdZY',
    appId: '1:1067819777324:web:8d8698e50ae97e8a5b0089',
    messagingSenderId: '1067819777324',
    projectId: 'flutter-restaurant-17238',
    authDomain: 'flutter-restaurant-17238.firebaseapp.com',
    storageBucket: 'flutter-restaurant-17238.appspot.com',
    measurementId: 'G-VGTEFEDCHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY5iHynxE9guzSKhPKEwudPtnr-5WKIrg',
    appId: '1:1067819777324:android:f110b78fdd41d6dc5b0089',
    messagingSenderId: '1067819777324',
    projectId: 'flutter-restaurant-17238',
    storageBucket: 'flutter-restaurant-17238.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-Os8ctwtE-n9LPKl6GqUjMafxr1OM5zs',
    appId: '1:1067819777324:ios:bdab069b47449f355b0089',
    messagingSenderId: '1067819777324',
    projectId: 'flutter-restaurant-17238',
    storageBucket: 'flutter-restaurant-17238.appspot.com',
    iosBundleId: 'com.example.projectx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-Os8ctwtE-n9LPKl6GqUjMafxr1OM5zs',
    appId: '1:1067819777324:ios:bdab069b47449f355b0089',
    messagingSenderId: '1067819777324',
    projectId: 'flutter-restaurant-17238',
    storageBucket: 'flutter-restaurant-17238.appspot.com',
    iosBundleId: 'com.example.projectx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-KxVekNTrEzxLAwiRSq1WVEC7oi2VdZY',
    appId: '1:1067819777324:web:471864a290b426785b0089',
    messagingSenderId: '1067819777324',
    projectId: 'flutter-restaurant-17238',
    authDomain: 'flutter-restaurant-17238.firebaseapp.com',
    storageBucket: 'flutter-restaurant-17238.appspot.com',
    measurementId: 'G-QR96NRRN1M',
  );
}
